hyperv:
  host: 192.168.1.121
  user: ad\\administrator
  password: ''
  vm_path: B:\\hyper-v\\
  cacert_path: certs/rootca.pem
  cert_path: certs/host.pem
  key_path: certs/host-key.pem
switch:
  name: wan
  net_adapter_names:
    - Ethernet
vms:
  - name_prefix: Win11
    count: 1
    iso_path: \\B:\\share\\isos\\win11.iso
    vhd_size_bytes: 60737421312
    memory_startup_bytes: 2147483648
    memory_maximum_bytes: 4294967296
    memory_minimum_bytes: 536870912
    processor_count: 2
