site_name: OpenTofu Lab Automation
site_description: Cross-platform OpenTofu lab automation project
site_author: OpenTofu Lab Team
site_url: https://github.com/your-username/opentofu-lab-automation

repo_name: opentofu-lab-automation
repo_url: https://github.com/your-username/opentofu-lab-automation

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.highlight

nav:
  - Home: README.md
  - Documentation:
    - Installation: docs/CONTRIBUTING.md
    - Automation Guide: docs/AUTOMATION-QUICKREF.md
    - CodeFixer Guide: docs/CODEFIXER-GUIDE.md
    - GUI Troubleshooting: docs/GUI-TROUBLESHOOTING.md
    - Branching Strategy: docs/BRANCHING-STRATEGY.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings

docs_dir: docs
site_dir: site
