extends: default
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  trailing-spaces: enable
  empty-lines:
    max: 2
  truthy:
    allowed-values: [true, false]
    check-keys: true
  comments:
    min-spaces-from-content: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
