---
extends: default
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  trailing-spaces: enable
  empty-lines:
    max: 2
  truthy:
    allowed-values: [true, false, 'on']  # Allow 'on' for GitHub Actions
    check-keys: false  # Don't check keys to allow GitHub Actions keywords
  comments:
    min-spaces-from-content: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  document-start:
    present: false  # Don't require --- at start of all documents
