name: Lint
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: .github/actions/lint/requirements.txt
    - name: Cache PowerShell modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/powershell/Modules
          ~/Documents/PowerShell/Modules
        key: ${{ runner.os }}-lint-psmodules-${{ hashFiles('.github/actions/lint/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-lint-psmodules-
    - name: Install ruff
      shell: bash
      run: pip install "ruff>=0.1"
    - name: Resolve Locked PSScriptAnalyzer Module
      shell: pwsh
      run: |
        Remove-Module -Name PSScriptAnalyzer -Force -ErrorAction SilentlyContinue
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    - name: Run Script Analyzer
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error,Warning -EnableExit -ErrorAction Stop
    - name: Run ruff
      shell: bash
      run: ruff check .
