---
name: "🔄 Auto-Merge PRs"

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: "🔄 Auto-Merge Eligible PRs"
    runs-on: ubuntu-latest
    steps:
      - name: Merge eligible PRs
        run: |
          for pr in $(gh pr list --state open --json number,mergeable -q '.[] | select(.mergeable=="MERGEABLE") | .number'); do
            echo "Attempting to merge PR #$pr..."
            if ! gh pr merge "$pr" --merge --auto --delete-branch; then
              echo "Failed to merge PR #$pr" >&2
            else
              echo "Successfully merged PR #$pr"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
