---
name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  # Quick validation job that runs first
  validate:
    name: Quick Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [".github/workflows/*.yml"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          if ! pip install -r scripts/requirements.txt; then
            echo "Failed to install Python dependencies" >&2
            exit 1
          fi

      - name: Validate workflow file
        run: |
          echo "Validating ${{ matrix.file }}..."
          if ! python3 scripts/validate-workflows.py ${{ matrix.file }}; then
            echo "Validation failed for ${{ matrix.file }}" >&2
            exit 1
          fi

      - name: Log validation success
        if: success()
        run: echo "Validation successful for ${{ matrix.file }}."

  # Summary of all jobs status
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [validate]
    if: always()
    steps:
      - name: Check results and provide summary
        run: |
          echo "  # # CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Validation | ${{ needs.validate.result }} |" >> $GITHUB_STEP_SUMMARY

          if ["${{ needs.validate.result }}" = "failure"]; then
            echo "❌ Validation failed - check logs for details"
            exit 1
          else
            echo "✅ Quick validation completed successfully"
            echo "Other workflows (lint, pester, pytest, test) will run independently"
          fi
