name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if ! command -v pwsh >/dev/null 2>&1; then
            if [[ "$RUNNER_OS" == "Linux" ]]; then
              sudo snap install powershell --classic
            elif [[ "$RUNNER_OS" == "macOS" ]]; then
              brew install --cask powershell
            fi
          fi
      - uses: ./.github/actions/lint
  pester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if ! command -v pwsh >/dev/null 2>&1; then
            if [[ "$RUNNER_OS" == "Linux" ]]; then
              sudo snap install powershell --classic
            elif [[ "$RUNNER_OS" == "macOS" ]]; then
              brew install --cask powershell
            fi
          fi

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser
      - name: Run Pester
        shell: pwsh
        run: |
          Invoke-Pester -CI -ErrorAction Stop
