name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # Quick validation job that runs first
  validate:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Validate workflow files
        run: |
          echo "Validating GitHub Actions workflow syntax..."
          for workflow in .github/workflows/*.yml; do
            echo "Checking $workflow"
            # Basic YAML syntax validation
            python3 -c "
            import yaml
            import sys
            try:
                with open('$workflow', 'r') as f:
                    yaml.safe_load(f)
                print('✓ $workflow syntax is valid')
            except Exception as e:
                print(f'✗ $workflow has syntax error: {e}')
                sys.exit(1)
            "
          done
          
      - name: Check repository structure
        run: |
          echo "Checking critical paths..."
          critical_paths=(
            "tests/"
            "pwsh/"
            "configs/"
            ".github/workflows/"
            "tests/PesterConfiguration.psd1"
            "pwsh/PSScriptAnalyzerSettings.psd1"
          )
          
          for path in "${critical_paths[@]}"; do
            if [ -e "$path" ]; then
              echo "✓ $path exists"
            else
              echo "✗ $path missing"
              exit 1
            fi
          done

  # Summary of all jobs status
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [validate]
    if: always()
    steps:
      - name: Check results and trigger other workflows
        run: |
          echo "## CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY  
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Validation | ${{ needs.validate.result }} |" >> $GITHUB_STEP_SUMMARY
          
          echo "✅ Quick validation completed"
          echo "Other workflows (lint, pester, pytest, test) will run independently"
