name: Copilot Auto Fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  copilot-suggest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate the GitHub CLI once with your PAT
      - name: Authenticate gh
        run: echo "${{ secrets.GH_PAT_AUTOPILOT }}" | gh auth login --with-token

      # Disable analytics / prompts so the CLI never pauses
      - name: Pre-seed Copilot config (headless)
        run: |
          mkdir -p "$HOME/.config/gh-copilot"
          cat <<EOF > "$HOME/.config/gh-copilot/config.yml"
          optional_analytics: false
          suggest_execute_confirm_default: false
          EOF

      # Install or upgrade the Copilot CLI extension
      - name: Install Copilot extension
        run: gh extension install github/gh-copilot --force

      # Loop through open issues → ask Copilot → add comment
      - name: Suggest fixes for each open issue
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_AUTOPILOT }}
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            title=$(gh issue view "$num" --json title -q .title)
            body=$(gh issue view "$num"  --json body  -q .body)

            prompt="Propose a concise git diff or detailed steps to fix issue #$num ($title) in ${{ github.repository }}.\n\nContext:\n$body"
            gh copilot suggest "$prompt" -w 0 > suggestion.md || true

            if [ -s suggestion.md ]; then
              gh issue comment "$num" -F suggestion.md
            else
              echo "No suggestion generated for issue #$num"
            fi
          done
