---
name: " Copilot Auto-Fix"

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sunday at 1 AM UTC
    - cron: '0 1 * * 0'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  copilot-suggest:
    name: " Generate AI-powered Fix Suggestions"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.COPILOT_OAUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Fail if GH_TOKEN missing
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "::error::COPILOT_OAUTH_TOKEN secret not set"
            exit 1
          fi

      # 'gh' will authenticate automatically via GH_TOKEN

      # Headless defaults  never prompt
      - name: Pre-seed Copilot config
        run: |
          mkdir -p "$HOME/.config/gh-copilot"
          cat >"$HOME/.config/gh-copilot/config.yml" <<'YAML'
          optional_analytics: false
          suggest_execute_confirm_default: false
          YAML

      # Install or upgrade the Copilot extension
      - name: Install Copilot extension
        run: gh extension install github/gh-copilot --force

      # Ask Copilot and comment back
      - name: Suggest fixes for each open issue
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            title=$(gh issue view "$num" --json title -q .title)
            body=$(gh issue view "$num"  --json body  -q .body)

            prompt="Propose a concise git diff or detailed steps to fix issue  # $num ($title) in ${{ github.repository }}.\n\nContext:\n$body"
            gh copilot suggest "$prompt" > suggestion.md || true            if [ -s suggestion.md ]; then
              gh issue comment "$num" -F suggestion.md
            else
              echo "No suggestion generated for issue #$num"
            fi
          done
