name: Copilot Auto Fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  comment-suggestions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate gh
        shell: bash
        run: echo "${{ secrets.GH_PAT_AUTOPILOT }}" | gh auth login --with-token
      - name: Install Copilot extension
        run: gh extension install github/gh-copilot --force
      - name: Suggest fixes for each open issue
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            gh copilot suggest "Fix issue #$num in ${{ github.repository }}" > suggestion.md || true
            gh issue comment "$num" -F suggestion.md

          done

  auto-fix:
    runs-on: ubuntu-latest
    needs: comment-suggestions
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate gh
        shell: bash
        run: echo "${{ secrets.GH_PAT_AUTOPILOT }}" | gh auth login --with-token
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Copilot CLI
        run: npm install -g @githubnext/github-copilot-cli
      - name: Run Copilot suggestions
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            body=$(gh issue view "$num" --json body -q .body)
            echo "$body" > issue.txt
            github-copilot-cli suggest --repo ${{ github.repository }} --issue issue.txt || true
          done
