name: Copilot-CLI Suggest
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate gh
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Copilot extension
        run: gh extension install github/gh-copilot --force

      - name: Suggest fixes for each open issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            # Get Copilot’s suggestion
            gh copilot suggest "Fix issue #$num in ${{ github.repository }}" > suggestion.md || true
            # Post it back to the issue
            gh issue comment "$num" -F suggestion.md

          done
