name: Copilot Auto FIx

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:

jobs:
  resolve_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Copilot CLI
        run: |
          npm install -g @githubnext/copilot-cli

      - name: Authenticate with GitHub token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Authenticated via GitHub Actions token."

      - name: Get open issues
        id: fetch_issues
        run: |
          gh issue list --state open --limit 10 --json number,title,body > issues.json

      - name: Run Copilot on issues
        run: |
          for row in $(jq -c '.[]' issues.json); do
            number=$(echo "$row" | jq -r '.number')
            title=$(echo "$row" | jq -r '.title')
            body=$(echo "$row" | jq -r '.body')
            suggestion=$(copilot suggest --context "$body")

            if [ -n "$suggestion" ]; then
              echo "Posting suggestion to issue #$number..."
              gh issue comment $number --body "🤖 Copilot suggests:

$suggestion"
            fi
          done
