name: Copilot Auto Fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  copilot-suggest:
    runs-on: ubuntu-latest
    # ① Expose the PAT so every gh command is already authenticated
    env:
      GH_TOKEN: ${{ secrets.GH_PAT_AUTOPILOT }}

    steps:
      - uses: actions/checkout@v4

      # ② Disable analytics / confirmation prompts
      - name: Pre-seed Copilot config (headless)
        run: |
          mkdir -p "$HOME/.config/gh-copilot"
          cat >"$HOME/.config/gh-copilot/config.yml" <<'EOF'
          optional_analytics: false
          suggest_execute_confirm_default: false
          EOF

      # ③ Install or upgrade the Copilot CLI extension
      - name: Install Copilot extension
        run: gh extension install github/gh-copilot --force

      # ④ Loop through open issues → ask Copilot → comment the answer
      - name: Suggest fixes for each open issue
        run: |
          for num in $(gh issue list --state open --json number -q '.[].number'); do
            title=$(gh issue view "$num" --json title -q .title)
            body=$(gh issue view "$num"  --json body  -q .body)

            prompt="Propose a concise git diff or detailed steps to fix issue #$num ($title) in ${{ github.repository }}.\n\nContext:\n$body"
            gh copilot suggest "$prompt" > suggestion.md || true

            if [ -s suggestion.md ]; then
              gh issue comment "$num" -F suggestion.md
            else
              echo "No suggestion generated for issue #$num"
            fi
          done
