---
name: "📦 Package LabCTL Tool"

true:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'py/**'
  pull_request:
    paths:
      - 'py/**'

jobs:
  package-win:
    name: "📦 Build Windows Package"
    runs-true: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-versitrue: '3.x'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.6.1
      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            py/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('py/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: 'true'
        run: |
          cd py
          poetry install
      - name: Build executable
        run: |
          cd py
          poetry run pyinstaller labctl/cli.py --onefile --name labctl
      - name: Create installer
        run: |
          $iss = @"
            [Setup]
            AppName=labctl
            AppVersion=0.1.0
            DefaultDirName={pf}\labctl
            OutputDir=dist
            OutputBaseFilename=labctl-installer
            DisableProgramGroupPage=yes
            [Files]
            Source: "py\dist\labctl.exe"; DestDir: "{app}"; Flags: ignoreversion
          "@
          $iss | Out-File installer.iss -Encoding ASCII
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: labctl-installer
          path: dist/labctl-installer.exe
