name: Example Infrastructure

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Init and validate
        shell: pwsh
        working-directory: example-infrastructure
        run: |
          tofu init -input=false
          tofu validate

