---
name: Example Infrastructure

on:
  push:
  pull_request:

jobs:
  linux-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Cache OpenTofu providers
        uses: actions/cache@v4
        with:
          path: opentofu/examples/hyperv/.terraform/providers
          key: ${{ runner.os }}-tofu-providers-${{ hashFiles('opentofu/examples/hyperv/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tofu-providers-
      - name: Init and validate
        working-directory: opentofu/examples/hyperv
        run: |
          tofu init -input=false 2>&1 | tee init.log
          tofu validate 2>&1 | tee validate.log
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-validate-logs
          path: |
            opentofu/examples/hyperv/init.log
            opentofu/examples/hyperv/validate.log
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-validate-artifacts
          path: opentofu/examples/hyperv/.terraform

  windows-validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: Cache OpenTofu providers
        uses: actions/cache@v4
        with:
          path: opentofu/examples/hyperv/.terraform/providers
          key: ${{ runner.os }}-tofu-providers-${{ hashFiles('opentofu/examples/hyperv/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tofu-providers-
      - name: Init and validate
        shell: pwsh
        working-directory: opentofu/examples/hyperv
        run: |
          $ErrorActionPreference = 'Stop'
          try {
            tofu init -input=false | Tee-Object -FilePath init.log
            tofu validate | Tee-Object -FilePath validate.log
            Write-Host "OpenTofu validation completed successfully" -ForegroundColor Green
          } catch {
            Write-Error "OpenTofu validation failed: $_"
            exit 1
          }
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-validate-logs
          path: |
            opentofu/examples/hyperv/init.log
            opentofu/examples/hyperv/validate.log
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-validate-artifacts
          path: opentofu/examples/hyperv/.terraform
